### ISSUE TITLE
Is there only one attention map for a single modality?

### ISSUE THREAD

**Issue by 17Skye17** [pomonam/AttentionCluster#1]
Hello Juhan Bae,

This repo for **Attention Cluster** is nice, after reading the corresponding paper I have a question about the number of  clusters. It seems that you implement the attention cluster with only one attention map for each modality, while in the official paper there are many clusters(many attention maps) for each modality (rgb & audio), so maybe a loop should be introduced in  `class AttentionClusterModel()` in `frame_level_model.py` ?  :- )

Best wishes,
Skye

**Comment by pomonam** [comment]
Hi,

Sorry for the late response; I just checked the issue. Yes, the paper introduces many clusters. If you take a look at 'AttentionClusterModule', it keeps track of 3D Tensor with size 'batch_size x feature_size x cluster_size' and uses matrix multiplication instead of loop to keep the code efficient. Hope this helps.

JB

**Comment by 17Skye17** [comment]
Hello, 

This helps me. I noticed this is a matrix multiplication a few days ago, so every row is a attention vector that can do multiplication with all frames of a single modality, I confused clusters with multi-head attention. Thank you : )!

Best wishes,
Skye
