### ISSUE TITLE
Train on other video datasets

### ISSUE THREAD

**Issue by ekazakos** [pomonam/AttentionCluster#2]
Hi,

Thanks a lot for your code! Could you provide some general guidelines on how extracted video/audio features from any dataset should be prepared to train the frame-level AttentionClusterModule? Thanks. :)

**Comment by pomonam** [comment]
Hi,

In this experiment, I used YouTube-8M dataset, which uses the Inception network trained on ImageNet and extract features from last hidden layer, before the classification layer. After that, it applies PCA. (you can find the details https://arxiv.org/pdf/1609.08675v1.pdf). I guess the most straightforward method is to get the pre-trained model and fetch features right before the classification layer. 

Juhan

**Comment by ekazakos** [comment]
Thanks for your answer. How many features per video the dataset has? And also in your implementation, do you follow the paper to sample randomly 20 features per video during training?

**Comment by pomonam** [comment]
Yes, it should be exactly the same as the paper, because the dataset has pre-computed features. If I remember correctly, each video has 1024 x m and 128 x m video and audio features, where m is the number of frames; it varies between videos. You can modify the cap here https://github.com/pomonam/AttentionCluster/blob/master/readers.py#L134.
